version: '3.8'

services:

  web:
    build: Web/
    ports:
      - "80:80"
    networks:
      memory-game-network:
        ipv4_address: 172.20.0.4

  db:
    build: Database/
    ports:
      - "3306:3306"
    networks:
      memory-game-network:
        ipv4_address: 172.20.0.3

  api:
    build: API/
    ports:
      - "8000:8000"
    networks:
      memory-game-network:
        ipv4_address: 172.20.0.2

networks:
  memory-game-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
