FROM python:3.11-alpine

# Moves the code over to /app
WORKDIR /app
COPY . .

# Installs the required packages
RUN pip3 install -r requirements.txt

# Exposes port 8000
EXPOSE 8000

CMD [ "uvicorn", "main:app" ]