# Use the official Nginx image
FROM nginx:alpine

# Copy the HTML files into the Nginx server directory
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Command to start Nginx
CMD ["nginx", "-g", "daemon off;"]
